services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: flowguard
      POSTGRES_USER: flowguard_user
      POSTGRES_PASSWORD: flowguard_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  capture:
    build: ./capture-cpp
    volumes:
      - ./data:/app/data
    cap_add:
      - NET_ADMIN
      - NET_RAW

  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
      - capture
    environment:
      DATABASE_URL: "postgresql://flowguard_user:flowguard_pass@postgres:5432/flowguard?schema=public"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"

  dashboard:
    build: ./dashboard
    ports:
      - "8080:80"
    depends_on:
      - ml-service

volumes:
  pgdata:
